main: co.crystaldev.factions.SimpleFactions
name: ${pluginName}Simple
description: ${pluginDescription}
version: ${pluginVersion}
authors: [ BestBearr ]
api-version: 1.13
depend:
  - AlpineCore
  - AlpineFactions
