name: "Deploy Snapshot"

on:
  push:
    branches: [master]

jobs:
  build_deploy_snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: "Checkout source"
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Set up JDK"
        # https://github.com/actions/setup-java/releases
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: temurin
          java-version: 17

      - name: "Setup Gradle"
        # https://github.com/gradle/actions/releases
        uses: gradle/actions/setup-gradle@8379f6a1328ee0e06e2bb424dadb7b159856a326 # v4.4.0
        with:
          validate-wrappers: true
          gradle-version: wrapper
          cache-disabled: false

      - name: "Build artifacts"
        run: ./gradlew build -Psnapshot=true --full-stacktrace

      - name: "Publish artifacts"
        run: ./gradlew publish -Psnapshot=true --full-stacktrace
        env:
          ALPINE_MAVEN_NAME: ${{ secrets.ALPINE_MAVEN_NAME }}
          ALPINE_MAVEN_SECRET: ${{ secrets.ALPINE_MAVEN_SECRET }}
